<a href="https://colab.research.google.com/github/Kambey-san/PyTorch_base/blob/HW_lesson_01/HW_lesson_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch

In [25]:
# Создайте случайный FloatTensor размера 3x4x5
t1 = torch.randn(3, 4, 5)
t1

tensor([[[ 0.7873,  0.1958,  0.7868, -1.1589,  0.7202],
         [-1.4972, -0.3958,  0.6211,  0.1182,  1.1744],
         [-0.0463, -0.5327, -0.9258, -0.8362, -0.4485],
         [-0.5686, -0.7132, -0.8629,  0.0575,  0.6163]],

        [[-1.4717,  1.1899, -1.5603,  1.1302, -0.6011],
         [ 0.4777, -0.0937,  1.2880,  0.2112,  0.6055],
         [ 1.0819,  0.2873,  0.6832,  0.8445,  1.3974],
         [-0.6319, -0.9471,  0.4325, -0.6953,  1.5292]],

        [[ 0.3719,  1.3561,  1.3123, -0.9338, -0.9313],
         [ 0.5146, -0.4204, -1.0299,  1.2796, -0.4595],
         [ 0.0935, -0.1617, -1.8037,  0.5391,  0.6693],
         [-2.0460, -1.1575,  0.1419,  0.0584,  1.6032]]])

In [26]:
# Выведите его форму (shape)
print(f'Форма тензора t1: {t1.shape}')

Форма тензора t1: torch.Size([3, 4, 5])


In [27]:
# Приведите его к форме 6 X 10
t1 = torch.reshape(t1, [6, 10])
t1, t1.shape

(tensor([[ 0.7873,  0.1958,  0.7868, -1.1589,  0.7202, -1.4972, -0.3958,  0.6211,
           0.1182,  1.1744],
         [-0.0463, -0.5327, -0.9258, -0.8362, -0.4485, -0.5686, -0.7132, -0.8629,
           0.0575,  0.6163],
         [-1.4717,  1.1899, -1.5603,  1.1302, -0.6011,  0.4777, -0.0937,  1.2880,
           0.2112,  0.6055],
         [ 1.0819,  0.2873,  0.6832,  0.8445,  1.3974, -0.6319, -0.9471,  0.4325,
          -0.6953,  1.5292],
         [ 0.3719,  1.3561,  1.3123, -0.9338, -0.9313,  0.5146, -0.4204, -1.0299,
           1.2796, -0.4595],
         [ 0.0935, -0.1617, -1.8037,  0.5391,  0.6693, -2.0460, -1.1575,  0.1419,
           0.0584,  1.6032]]),
 torch.Size([6, 10]))

In [28]:
# Создайте случайный IntTensor размера 10
t2 = torch.IntTensor(10)
t2.type(), t2

('torch.IntTensor',
 tensor([ 540680804,  842019362,  959458611, 1412641325,  893008176,  808663600,
          942748718, 1513502520,  572533794, 1701864804], dtype=torch.int32))

In [29]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
t1 * t2

tensor([[ 4.2570e+08,  1.6484e+08,  7.5488e+08, -1.6372e+09,  6.4311e+08,
         -1.2107e+09, -3.7315e+08,  9.4001e+08,  6.7676e+07,  1.9986e+09],
        [-2.5021e+07, -4.4857e+08, -8.8827e+08, -1.1812e+09, -4.0055e+08,
         -4.5982e+08, -6.7238e+08, -1.3060e+09,  3.2943e+07,  1.0489e+09],
        [-7.9571e+08,  1.0019e+09, -1.4970e+09,  1.5965e+09, -5.3677e+08,
          3.8633e+08, -8.8377e+07,  1.9494e+09,  1.2094e+08,  1.0304e+09],
        [ 5.8497e+08,  2.4192e+08,  6.5554e+08,  1.1930e+09,  1.2479e+09,
         -5.1102e+08, -8.9286e+08,  6.5457e+08, -3.9811e+08,  2.6025e+09],
        [ 2.0106e+08,  1.1419e+09,  1.2591e+09, -1.3192e+09, -8.3164e+08,
          4.1611e+08, -3.9635e+08, -1.5588e+09,  7.3263e+08, -7.8193e+08],
        [ 5.0547e+07, -1.3616e+08, -1.7306e+09,  7.6157e+08,  5.9773e+08,
         -1.6545e+09, -1.0912e+09,  2.1471e+08,  3.3415e+07,  2.7285e+09]])

In [30]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
t1 @ t1.T

tensor([[ 7.3161,  1.1052, -3.0383,  4.7765,  0.3704,  3.9792],
        [ 1.1052,  4.0032, -0.7275, -0.6045, -0.0696,  3.8587],
        [-3.0383, -0.7275,  9.9619, -1.0791, -2.5260,  2.9881],
        [ 4.7765, -0.6045, -1.0791,  8.6912, -2.3663,  5.0745],
        [ 0.3704, -0.0696, -2.5260, -2.3663,  8.7895, -5.0526],
        [ 3.9792,  3.8587,  2.9881,  5.0745, -5.0526, 12.1468]])

In [31]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(0.5, requires_grad = True)
t = torch.tensor(2.0, requires_grad = True)

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() #считаем производную по всем переменным

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) #частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [32]:
# Создайте единичный тензор размера 5x6
t3 = torch.ones([5, 6])
t3, t3.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]))

In [36]:
import numpy

In [37]:
# Переведите его в формат numpy
t3.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)